### ISSUE TITLE
Unable to load secret on ASB

### ISSUE THREAD

**Issue by abessifi** [awslabs/aws-servicebroker-documentation#16]
### Problem

I'm running AWS Service Broker on OpenShift `3.7` and tried, according to [these instructions](https://github.com/awslabs/aws-servicebroker-documentation/blob/master/getting-started.md#manually-creating-secrets-to-autofill-aws-service-parameters), to hide some sensitive parameters from `Service Catalog` users (aws_access_key, aws_secret_key, etc).

I've correctly created the secret within the same namespace where the broker is running (`aws-service-broker` in my case) and updated the `broker-config` configmap. After restart, the broker bootstraped correctly but when it gets requests from the Service Catalog it didn't hide the parameters from the Service Provisiong Wizard.  I can see the following message in the broker logs:

```
[2019-03-06T16:24:32.778Z] [WARNING] - Unable to load secret 'aws-access-secret' from namespace ''
```

### Solution

Please add the following notes to [this documentation section](https://github.com/awslabs/aws-servicebroker-documentation/blob/master/getting-started.md#manually-creating-secrets-to-autofill-aws-service-parameters):

Make sure to set the `namespace` parameter to the ASB project's name so the broker can fetch the secrets.

```yaml
openshift:
  host: ""
  ca_file: ""
  bearer_token_file: ""
  image_pull_policy: "IfNotPresent"
  sandbox_role: "edit"
  keep_namespace: false
  keep_namespace_on_error: true
  namespace: <PUT NAMESPACE OF BROKER HERE>
```

If the `namespace` parameter is omitted the broker won't read the secrets.
